language: php
php:
  - "5.5"
  - "5.3"
before_script:
  - echo "zend.enable_gc=off" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
  - sh -c "[ $TRAVIS_PHP_VERSION = '5.5' ] && composer install --dev --no-interaction"
  - sh -c "[ $TRAVIS_PHP_VERSION = '5.5' ] || phpenv config-rm xdebug.ini"
  - php -i
script:
  - phpunit -c phpunit-$TRAVIS_PHP_VERSION.xml
after_script:
  - sh -c "[ $TRAVIS_PHP_VERSION = '5.5' ] && php vendor/bin/coveralls -v"