language: php
php:
  - "5.6"
  - "5.3"
before_script:
  - echo "zend.enable_gc=off" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
  - mkdir releases tests/.cache
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.6' ]; then composer install --dev --no-interaction; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3' ]; then phpenv config-rm xdebug.ini; fi"
  - php -i
script:
  - phpunit -c phpunit-$TRAVIS_PHP_VERSION.xml
after_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.6' ]; then php vendor/bin/coveralls -v; fi"